version: '3.8'

services:
  db:
    image: postgres:16
    container_name: coffee_db
    restart: always
    environment:
      - POSTGRES_DB=coffee_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      # To jest kluczowy element - wolumen, dzięki któremu baza nie znika
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: